---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 14
    groups:
      patch:
        patterns:
          - '*'
        update-types:
          - 'patch'
      minor:
        patterns:
          - '*'
        update-types:
          - 'minor'
      major:
        patterns:
          - '*'
        update-types:
          - 'major'
    commit-message:
      prefix: 'deps'
      include: 'scope'
    labels:
      - 'ci/cd'
