name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup R For SeverityEstimate
        uses: ./.github/actions/setup-r
      - name: Build Roxygen  Documentation
        run: make docs
      - name: Check For Non-Committed Documentation
        run: |
          if [[ $( git status --porcelain ) ]]; then
            echo "Please run roxygen2::roxygenize() and commit the changes."
            exit 1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup R For SeverityEstimate
        uses: ./.github/actions/setup-r
      - name: Run Lintr
        run: make lint
        env:
          LINTR_ERROR_ON_LINT: true
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup R For SeverityEstimate
        uses: ./.github/actions/setup-r
      - name: Run Tests
        run: make test-fast
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup R For SeverityEstimate
        uses: ./.github/actions/setup-r
      - name: Run Check
        run: make check
