name: 'ci'

'on':
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

jobs:
  docs:
    name: 'docs'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'setup R'
        uses: './.github/actions/setup-r'
      - name: 'build roxygen documentation'
        run: 'just docs'
      - name: 'check for non-committed documentation'
        run: |
          if [[ $( git status --porcelain ) ]]; then
            echo "Please run roxygen2::roxygenize() and commit the changes."
            exit 1
          fi
  lint:
    name: 'lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'setup R'
        uses: './.github/actions/setup-r'
      - name: 'install air'
        uses: 'posit-dev/setup-air@v1'
      - name: 'run lint'
        run: 'just lint'
  tests:
    name: 'tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'setup R'
        uses: './.github/actions/setup-r'
      - name: 'run tests'
        run: 'just test-fast'
  check:
    name: 'check'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'setup R'
        uses: './.github/actions/setup-r'
      - name: 'run check'
        run: 'just check'
  news:
    name: 'news'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6'
        with:
          fetch-depth: 0
      - name: 'check news updated'
        run: |
          git fetch origin main:main
          GIT_LOG=$(git log main..HEAD --pretty=format:"%s %b")
          SKIP_REGEX="no[[:space:]]+major[[:space:]]+changes"
          if echo "$GIT_LOG" | tr '\n' ' ' | grep -Eiq "$SKIP_REGEX"; then
            echo "Bypassing news check: 'no major changes' found in commit history"
            exit 0
          fi
          if ! git diff --name-only main...HEAD | grep -q "^NEWS.md$"; then
            echo "Error: Please update NEWS.md"
            exit 1
          fi
