# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures?
# Start at https://github.com/r-lib/actions#where-to-find-help
name: 'pkgdown'

'on':
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  release:
    types:
      - 'published'
  workflow_dispatch:

permissions: 'read-all'

jobs:
  pkgdown:
    runs-on: 'ubuntu-latest'
    concurrency:
      group: "pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}"
    env:
      GITHUB_PAT: "${{ secrets.GITHUB_TOKEN }}"
    permissions:
      contents: 'write'
    steps:
      - name: 'checkout repository'
        uses: 'actions/checkout@v6.0.3'
      - name: 'setup R'
        uses: './.github/actions/setup-r'
        with:
          install-dev-dependencies: 'true'
          install-pandoc: 'true'
          install-package: 'true'
      - name: 'build pkgdown site'
        run: "Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'"
      - name: 'deploy to github pages'
        if: "${{ github.event_name != 'pull_request' }}"
        uses: 'JamesIves/github-pages-deploy-action@v4.8.0'
        with:
          clean: false
          branch: 'gh-pages'
          folder: 'docs'
